### ISSUE TITLE
Wrong sync

### ISSUE THREAD

**Issue by declider** [lynxaegon/obsidian-anysocket-sync#12]
Hi! First of all, thanks for plugin! From all of them, it is best sync solution.
But it works wrong for me :(

For some reason PC Obsidian always copy files and it's content from Android obsidian, ignoring when it was updated. Even if i didn't touch phone-Obsidian for few days and have lot of changes in vault on PC-Obsidian, after sync all my edits in files will be gone, phone-Obsidian will get no old file updates, and PC-Obsidian will downgrade those files to their few-days old versions phone have.

So it's impossible for me to sync it without data loss.

**Comment by lynxaegon** [comment]
Hi, this is quite interesting because it should never happen. But i do have a few questions:
- is auto sync enabled?
- do you have roughly the same datetime on both pc/mobile/server?
- are you writing in obsidian (pc or mobile) while offline or online? (Active connection to anysocket server
- do you use other sync plugins or do you have the vault on dropbox?

The client works by capturing file updates (with server timestamp) and sending them to the server which decides which file is newer.

You ca always enable debug on both server and client and look into the logs and see what happens.

I've been using this since i made it and i never had any data loss, but i'm always online while editing notes

**Comment by declider** [comment]
- Yes, auto sync enabled, but wrong behavior is same with manual sync while autosync disabled.
- Yes, exact same datetime on both pc and mobile.
- When i first saw this plugin i turn on autostart server through Shell Commands plugin, and Anysync plugin was enabled and connected too. But after discovering a bug, i decided to turn it off for a while. After few days i tried to enable it again - same behavior.
- Anysync and FIT (git backup) are two plugins i use. No dropbox.
- Server is just local node.js on same PC that runs Obsidian, so there are only two devices, PC with obsidian and server, and Mobile.

I am trying some different approaches like having server and connection on PC always on, or having it both disabled, but it change nothing and i always lose my data when mobile opens and connects to server.

**Comment by lynxaegon** [comment]
Could you check the version history for a file that was wrongly synced? I want to know if you do have the correct versions there.

Without seeing any logs, i can only presume that the mobile is doing something shady and updating the server with older versions.

**Comment by declider** [comment]
I tested it, with timestamps and screenshots:
https://imgur.com/a/v2GWNuX
14:50 - have both devices connected, file looks same on both.
14:51 - closing mobile version, writing text in note
14:52 - still writing text in note, gonna enable mobile obsidian
14:53 - mobile obsidian enable, my text is gone, note downgraded to 14:50 version
14:54 - checking "modified" on mobile - it says "14:50", so it is indeed older version (it still says same "14:50" as i writing this comment)

How do i provide logs? I just checked "debug" in plugin settings, for both desktop and mobile versions

**Comment by declider** [comment]
Android Obsidian:
- Current version: 1.7.4 (167)
- API v1.7.4

About this:
> It seems the problem is on the mobile client, from what i suspect obsidian triggers a file update before it's connected to the server.
I don't know how valuable this info, but that file from my previous comment is still have "Last update: 11/04/20 14:50", even if i open Obsidian (without anysync plugin yet) and open this note from it - last update time doesn't change (and i didn't change in it by myself).

About logs: got it, will try to collect some and return with them.

**Comment by lynxaegon** [comment]
I have fixed the bug in the latest version, i'll push a new version in an hour

**Comment by declider** [comment]
Yep, tried few times, always works pefrect. Thanks!
