### ISSUE TITLE
Files reverted to previous version on launch Obsidian mobile

### ISSUE THREAD

**Issue by millerdev** [lynxaegon/obsidian-anysocket-sync#16]
After editing and renaming a few files on the desktop, I launched the mobile app and noticed that my recent desktop edits had been reverted.

Additionally, old versions of files that had been renamed (moved) on the desktop had been restored as their previous name, meaning that now there were two files: one with the old name, and one with the new.

It seems like the mobile app thought it had the latest version of every file and sent them over to clobber more recent changes on the desktop.

**Comment by lynxaegon** [comment]
Which version are you using?
There was an issue with this from 1.3.0 and it was fixed on 1.3.3.

**Comment by millerdev** [comment]
I was running 1.3.2. Now upgraded to 1.3.3. Will report back if it happens again. Feel free to close this ticket.
