### ISSUE TITLE
Delayed Sync

### ISSUE THREAD

**Issue by gooseleggs** [lynxaegon/obsidian-anysocket-sync#3]
I am evaluating this and perhaps looking to replace Remotely Sync plugin due to version history.  However, in testing, I get lots of version history due to it updating constantly.

Ie, If I type _Does this work_ and then delete it quite quickly, this gives me three versions:
1) Does this work
2) Does
3 (blank)

Can you add an adjustable delay to allow for pausing.  Maybe delay updates increments, like 5s, 10s, 20s, 30s, 1m (that is, if the page is modified within this timeframe then the sync counter starts at 0 again)?
Also, Can you add options to only perform manual sync?  Then you might just sync at start of session, then end of session?

**Comment by lynxaegon** [comment]
Hi, indeed right now it syncs based on Obsidian changes, which happen pretty often (around 2-3 seconds), but i can add an option to sync based on an adjustable delay (5s, 10s, 20s, etc) or a manual sync. 
I'll look into adding these on the roadmap

**Comment by lynxaegon** [comment]
The latest release [1.3.0](https://github.com/lynxaegon/obsidian-anysocket-sync/releases/tag/1.3.0) has an adjustable delay, you can try it out. It does exactly what you need
There is also an Auto Sync option (defaults to true) which you can toggle to disable/enable auto sync. In case auto sync is disabled, you will still be connected to the server, but you will never send/receive updates unless you open the command pallet and run `Sync Now`
