### ISSUE TITLE
Feature request: replace pop-up notifications with status bar connection indicator

### ISSUE THREAD

**Issue by millerdev** [lynxaegon/obsidian-anysocket-sync#7]
I find the _Connected / Not Connected / Lost connection_ pop-up notifications to be distracting. A connection status indicator in the status bar would be less distracting.

**Comment by lynxaegon** [comment]
After a few hours of using them, i do find them annoying. I'll look into moving the notifications to the status bar. Hopefully tomorrow there will be a new release 😄

**Comment by millerdev** [comment]
When I upgrade the plugin to 1.3.2 on one of my machines it immediately downgrades to v1.1.2. I didn't think it was syncing plugins, but I assume this is because the server has an earlier version and for some reason it thinks the files are newer? Should I file a separate ticket about that?

**Comment by lynxaegon** [comment]
That's normal behaviour. You need to upgrade the server and the server will push the new version to the clients when they connect.
Downgrading only happens if the client si newer tham the server.
I need to implement a better update system
