### ISSUE TITLE
Cannot manual sync

### ISSUE THREAD

**Issue by gooseleggs** [lynxaegon/obsidian-anysocket-sync#9]
I would assume that when you disable Auto-Sync that you can then perform a manual sync.  However, when this is the case, it connects to the server, and says autosync is disabled.  It does not update the server.  Can it be configured that when you trigger a sync that it performs an update even without AutoSync enabled?  This is using version 1.3.2.

**Comment by lynxaegon** [comment]
I'm sorry i'm a bit confused about your issue. Let me explain how it works:
- Auto Sync disabled - no file changes will be pushed from server nor from client. You need to manually run the sync now command - which will update files on both client & server
- auto sync enabled - every file change is pushed

**Comment by gooseleggs** [comment]
Thanks for the reply. I have figured out the issue. I am trialing it in iOS. When auto sync is disabled and I hit the _anysocket sync_ it gives me the issue as per the original post. 

![image](https://github.com/user-attachments/assets/4ad5b826-d0bd-4cb6-bf94-ed684d8a6ec0)


When I open the command palette I can run the sync now command and it works. Can you make the anysocket sync in the diagram perform the same action as the _sync now_ command?

**Comment by lynxaegon** [comment]
in the latest version 1.3.2, that menu item shouldn't exist. It has been removed

**Comment by gooseleggs** [comment]
I like that the item was there. I think it should just be the sync now option instead. I don’t want to have a full time connection for when I am on mobile data so prefer to decide when to sync. So having it in the quick access bar is helpful.
